name: Update Location Files

on:
  issue_comment:
    types: [created]

jobs:
  update-location:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last 10 comments on issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/real-CAK3D/real-CAK3D.github.io/issues/1/comments \
            | jq '[.[] | .body | fromjson]' > parsed_comments.json

      - name: Process comments and update files
        run: |
          count=$(jq length parsed_comments.json)
          echo "Total parsed comments: $count"

          # Handle at least 1 comment
          if [ "$count" -ge 1 ]; then
            jq '.[-1]' parsed_comments.json > location.json
          fi

          # If there's a second-to-last, save it too
          if [ "$count" -ge 2 ]; then
            jq '.[-2]' parsed_comments.json > location-prev.json
          else
            echo '{}' > location-prev.json
          fi

          # Move everything older than last 2 to location-history
          if [ "$count" -gt 2 ]; then
            jq '.[0:-2]' parsed_comments.json | jq -s -c 'flatten | .[]' \
            | jq -s -c 'join(",")' | sed 's/^"//;s/"$//' > location-history.json
          else
            echo "" > location-history.json
          fi

      - name: Generate map.html
        run: |
          lat=$(jq -r '.lat' location.json)
          lon=$(jq -r '.lon' location.json)
          prev_lat=$(jq -r '.lat' location-prev.json)
          prev_lon=$(jq -r '.lon' location-prev.json)

          cat <<EOF > map.html
<!DOCTYPE html>
<html>
  <head>
    <title>Dog Location</title>
    <style>
      iframe { width: 100%; height: 400px; border: none; }
      body { font-family: Arial, sans-serif; background: #f4f4f4; padding: 1rem; }
    </style>
  </head>
  <body>
    <h1>Most Recent Location</h1>
    <iframe src="https://www.google.com/maps?q=${lat},${lon}&output=embed"></iframe>

    <h2>Previous Location</h2>
    <p>Latitude: ${prev_lat}, Longitude: ${prev_lon}</p>
  </body>
</html>
EOF

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add location.json location-prev.json location-history.json map.html
          git commit -m "Update location files from issue comment" || echo "No changes to commit"
          git push