name: Update Location in README

on:
  issue_comment:
    types: [created]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request == null }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract lat/lon from comment
        id: extract
        run: |
          echo '${{ github.event.comment.body }}' > comment.json
          LAT=$(jq -r '.lat' comment.json)
          LON=$(jq -r '.lon' comment.json)

          if [[ "$LAT" == "null" || "$LON" == "null" ]]; then
            echo "❌ Latitude or Longitude not found in comment"
            exit 1
          fi

          echo "LAT=$LAT" >> $GITHUB_ENV
          echo "LON=$LON" >> $GITHUB_ENV

      - name: Replace FIRST iframe in README with updated map
        run: |
          NEW_IFRAME="<iframe src=\"https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d2865.2493525638047!2d$LON!3d$LAT!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2us!4v$(date +%s)000!5m2!1sen!2us\" width=\"400\" height=\"300\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>"

          sed -i -E "0,/<iframe[^<]*<\/iframe>/s||$NEW_IFRAME|" README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "📍 Update map to $LAT, $LON"
          git push