name: Update Location in README

on:
  issue_comment:
    types: [created]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request == null }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract lat/lon from comment
        id: extract
        run: |
          echo "${{ github.event.comment.body }}" > comment.json
          LAT=$(jq -r '.lat' comment.json)
          LON=$(jq -r '.lon' comment.json)
          if [[ "$LAT" == "null" || "$LON" == "null" ]]; then
            echo "Latitude or Longitude not found in the comment."
            exit 1
          fi
          echo "LAT=$LAT" >> $GITHUB_ENV
          echo "LON=$LON" >> $GITHUB_ENV

      - name: Update coordinates in README
        run: |
          perl -0777 -i -pe 's/(!2d)([-0-9.]+)(!3d)([-0-9.]+)/"${1}$ENV{LON}${3}$ENV{LAT}"/ge' README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update location to lat: $LAT, lon: $LON"
          git push