name: Update Location in README

on:
  issue_comment:
    types: [created]

jobs:
  update-readme-location:
    if: contains(github.event.comment.body, 'lat') && contains(github.event.comment.body, 'lon')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract latitude and longitude from comment
        id: get_location
        run: |
          echo '${{ github.event.comment.body }}' > comment.json
          lat=$(jq '.lat' comment.json)
          lon=$(jq '.lon' comment.json)
          echo "lat=$lat" >> $GITHUB_OUTPUT
          echo "lon=$lon" >> $GITHUB_OUTPUT

      - name: Update iframe in README
        run: |
          lat=${{ steps.get_location.outputs.lat }}
          lon=${{ steps.get_location.outputs.lon }}
          echo "Updating README.md with lat: $lat and lon: $lon"

          # Replace !2dLONG!3dLAT in the iframe URL
          sed -i -E "s/!2d-?[0-9]+\.[0-9]+!3d-?[0-9]+\.[0-9]+/!2d${lon}!3d${lat}/" README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add README.md
          git commit -m "📍 Update map location to lat: ${{ steps.get_location.outputs.lat }}, lon: ${{ steps.get_location.outputs.lon }}" || echo "No changes to commit"
          git push