name: Update Map Location

on:
  issue_comment:
    types: [created]

jobs:
  update-map:
    if: contains(github.event.comment.body, 'lat') && contains(github.event.comment.body, 'lon')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse coordinates from comment
        id: get_location
        run: |
          echo '${{ github.event.comment.body }}' > comment.json
          LAT=$(jq -r '.lat' comment.json)
          LON=$(jq -r '.lon' comment.json)
          echo "LAT=$LAT" >> $GITHUB_ENV
          echo "LON=$LON" >> $GITHUB_ENV

      - name: Replace coordinates in README
        run: |
          echo "Replacing map coordinates in README.md..."
          sed -i -E "s/!2d[-0-9.]+!3d[-0-9.]+/!2d$LON!3d$LAT/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "📍 Update coordinates to lat: $LAT, lon: $LON" || echo "No changes to commit"
          git push